name: starter-kit

services:
  postgres:
    image: postgres:17-alpine
    container_name: starter-postgres
    env_file:
      - ./db/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/sql/db_schema_dump.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:

networks:
  localnet:
    driver: bridge
