services:
  postgres:
    image: postgres:17-alpine
    container_name: app-postgres
    env_file:
      - ./db/.env.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - localnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # We can comment out this if we use some other tool like DBeaver, anyway this will not be never hosted
  pgadmin:
    image: dpage/pgadmin4
    container_name: app-pgadmin
    env_file:
      - ./db/.env.dev
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - localnet
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:

networks:
  localnet:
    driver: bridge
