spring:
  datasource:
    url: jdbc:postgresql://${DB_HOSTNAME}/${DB_DATABASE}?autoReconnect=true
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

  jpa:
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}

logging:
  level:
    root: INFO
    com.slobodanzivanovic.backend: TRACE
    org.springframework: INFO
    org.hibernate: INFO

springdoc:
  swagger-ui:
    enabled: true
